package vn.co.cex.orm;

// Generated Jan 28, 2015 9:41:06 PM by Hibernate Tools 4.0.0

/**
 * CityNameID generated by hbm2java
 */
public class LanguageNameID implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1924445268474669097L;
	private String code;
	private String languageCode;
	public LanguageNameID() {
	}

	public LanguageNameID(String code, String languageCode) {
		this.code = code;
		this.languageCode = languageCode;
	}

	
	/**
	 * @return the code
	 */
	public String getCode() {
		return code;
	}

	/**
	 * @param code the code to set
	 */
	public void setCode(String code) {
		this.code = code;
	}

	public String getLanguageCode() {
		return this.languageCode;
	}

	public void setLanguageCode(String languageCode) {
		this.languageCode = languageCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LanguageNameID))
			return false;
		LanguageNameID castOther = (LanguageNameID) other;

		return (this.getCode() == castOther.getCode())
				&& ((this.getLanguageCode() == castOther.getLanguageCode()) || (this
						.getLanguageCode() != null
						&& castOther.getLanguageCode() != null && this
						.getLanguageCode().equals(castOther.getLanguageCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (this.getCode() == null ? 0: this.getCode().hashCode());
		result = 37* result + (getLanguageCode() == null ? 0 : this.getLanguageCode()
						.hashCode());
		return result;
	}

}
